/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export interface Admin {
  country_code: string;
  email: string;
  name: string;
  password: string;
  phone: number;
}
